version: "3"

services:
    telegramail:
        build: .
        container_name: telegramail
        restart: unless-stopped
        volumes:
            - ./.env:/app/.env
        environment:
            - TZ=Asia/Shanghai
