version: "3.8"

services:
    telegramail:
        image: logictan/telegramail:latest
        container_name: telegramail
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./data:/app/data
