[tools]
python = "3.10"
lima = "1.0.7"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.dev]
run = "python -m app.main"

[tasks.dev-docker]
description = "Local development with Docker"
run = [
    "limactl start",
    "lima nerdctl container rm -f telegramail",
    "lima nerdctl build -t logictan/telegramail:dev -f Dockerfile .",
    "lima nerdctl run -i -t --env-file=.env --name telegramail --rm logictan/telegramail:dev"
]

[tasks.pip]
run = "pip install -r requirements.txt"

[tasks.i18n]
run = "python scripts/check_i18n.py"

[tasks.setup-tdlib]
run = "python scripts/setup_tdlib.py"

[tasks.init]
run = [
    "mise run pip",
    "mise run setup-tdlib",
]