[tools]
python = "3.10"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.dev]
run = "python -m app.main"

[tasks.pip]
run = "pip install -r requirements.txt"

[tasks.i18n]
run = "python scripts/check_i18n.py"