"""
Stores configurations for common email providers.
"""

COMMON_PROVIDERS = [
    {
        "name": "Gmail",
        "smtp_server": "smtp.gmail.com",
        "smtp_port": 465,
        "smtp_ssl": True,
        "imap_server": "imap.gmail.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "Outlook/Hotmail",
        "smtp_server": "smtp-mail.outlook.com",
        "smtp_port": 587,
        "smtp_ssl": False,
        "smtp_starttls": True,
        "imap_server": "outlook.office365.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "Yahoo Mail",
        "smtp_server": "smtp.mail.yahoo.com",
        "smtp_port": 465,
        "smtp_ssl": True,
        "imap_server": "imap.mail.yahoo.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "ProtonMail",
        "smtp_server": "smtp.protonmail.ch",
        "smtp_port": 465,
        "smtp_ssl": True,
        "imap_server": "imap.protonmail.ch",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "iCloud",
        "smtp_server": "smtp.mail.me.com",
        "smtp_port": 587,
        "smtp_ssl": False,
        "smtp_starttls": True,
        "imap_server": "imap.mail.me.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "Zoho Mail",
        "smtp_server": "smtp.zoho.com",
        "smtp_port": 465,
        "smtp_ssl": True,
        "imap_server": "imap.zoho.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "AOL",
        "smtp_server": "smtp.aol.com",
        "smtp_port": 465,
        "smtp_ssl": True,
        "imap_server": "imap.aol.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "GMX",
        "smtp_server": "mail.gmx.com",
        "smtp_port": 465,
        "smtp_ssl": True,
        "imap_server": "imap.gmx.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "QQ Mail",
        "smtp_server": "smtp.qq.com",
        "smtp_port": 465,
        "smtp_ssl": True,
        "imap_server": "imap.qq.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "NetEase (163/126)",
        "smtp_server": "smtp.163.com",
        "smtp_port": 465,
        "smtp_ssl": True,
        "imap_server": "imap.163.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "Tencent Exmail",
        "smtp_server": "smtp.exmail.qq.com",
        "smtp_port": 465,
        "smtp_ssl": True,
        "imap_server": "imap.exmail.qq.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "Alibaba Mail",
        "smtp_server": "smtp.aliyun.com",
        "smtp_port": 465,
        "smtp_ssl": True,
        "imap_server": "imap.aliyun.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
    {
        "name": "Yandex",
        "smtp_server": "smtp.yandex.com",
        "smtp_port": 465,
        "smtp_ssl": True,
        "imap_server": "imap.yandex.com",
        "imap_port": 993,
        "imap_ssl": True,
    },
] 